services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    entrypoint: ["bash", "/mongo-entrypoint.sh"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-keyfile:/tmp/keyfile:ro
      - ./docker/mongo/replica-set-script.sh:/mongo-entrypoint.sh:ro
    environment:
      MONGO_INITDB_DATABASE: book-advisor-db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: unless-stopped

  mongo-init:
    image: mongo
    depends_on:
      - mongodb
    restart: "no"
    entrypoint: >
      mongosh --host mongodb:27017 
      -u ${MONGO_ROOT_USER} -p ${MONGO_ROOT_PASSWORD} --authenticationDatabase admin
      --eval "rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'mongodb:27017' }] })"

  mongodb-express:
    image: mongo-express:1.0.2
    container_name: mongo-express
    ports:
      - "8083:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongodb

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: book-advisor-db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-admin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "9090:9090"
    environment:
      PGADMIN_LISTEN_PORT: 9090
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_UI_AUTH: ${MAILPIT_LOGIN}:${MAILPIT_PASSWORD}

  redis:
    image: redis:7.4.8-alpine
    restart: always
    ports:
      - "6379:6379"
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  redis-admin:
    image: redis/redisinsight:latest
    container_name: redisinsight
    environment:
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "5540:5540"
    depends_on:
      - redis
    volumes:
      - redisinsight_data:/data

  #proxy-old:
  #  image:
  #    lukasz408/proxy:1.0
  #  expose:
  #      - "8000"
  #  environment:
  #    TIMEOUT: 50000
  #  labels:
  #    - "traefik.enable=true"
  #    - "traefik.http.routers.proxy.rule=Host(`proxy.localhost`)"
  #    - "traefik.http.routers.proxy.entrypoints=web"

  ## my local proxy for additional rotation
  tinyproxy:
    image: vimagick/tinyproxy
    ports:
      - "8888:8888"

  proxy:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=debug
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    volumes:
      - /var/lib/flaresolver:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`proxy.localhost`)"
      - "traefik.http.routers.proxy.entrypoints=web"

  traefik:
    image: traefik:v3.6.9
    container_name: traefik
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    depends_on:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo_data:
  postgres_data:
  redis_data:
  redisinsight_data:

