services:
  app:
    image: book-advisor-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8090:8090"
    volumes:
      - /home/lukasz/Documents/openlibrary/ol_dump_authors_2026-02-28.txt:/app/data/ol_dump_authors.txt:ro
      - /home/lukasz/Documents/openlibrary/ol_dump_works_2026-02-28.txt:/app/data/ol_dump_works.txt:ro
      - /home/lukasz/Documents/openlibrary/ol_dump_editions_2026-02-28.txt:/app/data/ol_dump_editions.txt:ro

  frontend:
    image: book-advisor-frontend
    build:
      context: ../personal-advisor
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://app:8090
    ports:
      - "3000:3000"