spring:
  mongodb:
    uri: mongodb://mongo_user:mongo_password@localhost:27017/admin
    database: book-advisor-db
  datasource:
    url: jdbc:postgresql://localhost:5435/book-advisor-db
    username: postgres
    password: password
  mail:
    host: localhost
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
        auth: false
        starttls:
          enable: false
        debug: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redis

  kafka:
    bootstrap-servers: localhost:29092


logging:
  level:
    io.github.luksal.integration.source.openlibrary: DEBUG
    io.github.luksal.integration.source.googlebooks: DEBUG
    io.github.luksal.integration.source.archivebooks: DEBUG

app:
  mail:
    from: noreply-book-advisor@gmail.com
    to: lukasz4088@gmail.com
  service:
    google-books-api:
      auth:
        api-keys: GOOGLE_BOOKS_API_KEYS
  ai:
    ollama:
      url: http://10.0.2.2:11434

  file-read:
    path:
      authors: /home/lukasz/Documents/openlibrary/ol_dump_authors_2026-02-28.txt
      works: /home/lukasz/Documents/openlibrary/ol_dump_works_2026-02-28.txt
      editions: /home/lukasz/Documents/openlibrary/ol_dump_editions_2026-02-28.txt
  proxies:
    - name: flaresolverr
      url: http://localhost:8191/v1
      max-timeout: 1000000
      forwarding-proxies-urls:
        - http://172.17.0.1:8888
      headers:
        "Content-Type" : "application/json"
        "Accept" : "application/json"
