server:
  address: 0.0.0.0
  port: 8090
  tomcat:
    threads:
      max: 100
      min-spare: 10

spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      auto-index-creation: true
    redis:
      client-type: lettuce
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-version: 0
    out-of-order: true
    baseline-on-migrate: true
    mixed: true
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
  cloud:
    openfeign:
      httpclient:
        max-connections: 5
        max-connections-per-route: 1
        connection-timeout: 10000

app:
  scraping:
    proxy:
      url: http://localhost:8191/v1
      max-timeout: 100000
  kafka:
    consumer:
      books-source-dlq-topic: book-advisor-db.books-dlq
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    connect:
      books-source-topic: book-advisor-db.books
      ratings-source-topic: book-advisor-db.ratings
      books-sink-topic: postgres.books



