spring:
  mongodb:
    uri: mongodb://mongo_user:mongo_password@mongodb:27017/admin
    database: book-advisor-db
  datasource:
    url: jdbc:postgresql://postgres:5432/book-advisor-db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  mail:
    host: mailpit
    port: 1025
    username: admin
    password: admin
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
        debug: true
  data:
    redis:
      host: redis
      port: 6379
      password: redis

  kafka:
    bootstrap-servers: kafka:9092


logging:
  level:
    io.github.luksal.integration.source.openlibrary: DEBUG
    io.github.luksal.integration.source.googlebooks: DEBUG
    io.github.luksal.integration.source.archivebooks: DEBUG

app:
  mail:
    from: noreply-book-advisor@gmail.com
    to: lukasz4088@gmail.com
  service:
    google-books-api:
      auth:
        api-keys: GOOGLE_BOOKS_API_KEYS
  ai:
    ollama:
      url: http://192.168.1.15:11434
  file-read:
    path:
      authors: /app/data/ol_dump_authors.txt
      works: /app/data/ol_dump_works.txt
      editions: /app/data/ol_dump_editions.txt
  proxies:
    - name: flaresolverr
      url: http://proxy:8191/v1
      max-timeout: 1000000
      forwarding-proxies-urls:
        - http://tinyproxy:8888
      headers:
        "Content-Type" : "application/json"
        "Accept" : "application/json"
    - name: decodo
      url: https://scraper-api.decodo.com/v2/scrape
      max-timeout: 100000
      forwarding-proxies-urls:
        - http://tinyproxy:8888
      headers:
        "Content-Type": "application/json"
        "Accept": "application/json"