server:
  address: 0.0.0.0
  port: 8090
  tomcat:
    threads:
      max: 100
      min-spare: 10

spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      pool-name: BookAdvisorHikariCP
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  data:
    jpa:
      repositories:
        enabled: true
    mongodb:
      auto-index-creation: true
    redis:
      client-type: lettuce
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
  flyway:
    schemas: public
    enabled: true
    baseline-version: 0
    out-of-order: true
    baseline-on-migrate: true
    mixed: true
  task:
    execution:
      pool:
        core-size: 10
        max-size: 20
        queue-capacity: 100
  cloud:
    openfeign:
      client:
        config:
          openLibraryClient:
            logger-level: basic
            url: https://openlibrary.org/
          googleBooksClient:
            logger-level: basic
            url: https://www.googleapis.com/
          archiveBooksClient:
            logger-level: basic
            url: https://archive.org/
      httpclient:
        max-connections: 5
        max-connections-per-route: 1
        connection-timeout: 10000
  kafka:
    admin:
      auto-create: true

app:
  scraping:
    proxy:
      url: http://localhost:8191/v1
      max-timeout: 100000
  kafka:
    consumer:
      books-source-dlq-topic: book-advisor-db.books-dlq
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    connect:
      books-source-topic: book-advisor-db.books
      ratings-source-topic: book-advisor-db.ratings
      books-sink-topic: postgres.books

resilience4j:
  ratelimiter:
    instances:
      search-openLibraryRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 6s
        timeoutDuration: 1s
      get-openLibraryRateLimiter:
        limitForPeriod: 55
        limitRefreshPeriod: 60s
        timeoutDuration: 20s
      search-googleBooksRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 3s
        timeoutDuration: 1s
      page-fetcherRateLimiter:
        limitForPeriod: 20
        limitRefreshPeriod: 1s
        timeoutDuration: 0

  circuitbreaker:
    instances:
      search-openLibraryCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 3m
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      search-googleBooksCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 24h
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        record-exceptions:
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - feign.FeignException.InternalServerError
      search-archiveBooksCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 24h
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        record-exceptions:
          - feign.FeignException.ServiceUnavailable
          - feign.FeignException.GatewayTimeout
          - feign.FeignException.InternalServerError
      crawl-ExtractRatingCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 2m
        permittedNumberOfCallsInHalfOpenState: 4
        automaticTransitionFromOpenToHalfOpenEnabled: true
        record-exceptions:
          - io.github.luksal.exception.SearchPageNotLoadedException

  retry:
    instances:
      search-openLibraryRetry:
        max-attempts: 4
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 40s
        retry-exceptions:
          - feign.RetryableException
      get-openLibraryRetry:
        max-attempts: 4
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 40s
        retry-exceptions:
          - feign.RetryableException
      page-fetcherRetry:
        max-attempts: 4
        wait-duration: 500ms
        exponential-backoff-multiplier: 2
        exponential-max-wait-duration: 40s


